### ISSUE TITLE
Multiple proposal(service_type) support

### ISSUE THREAD

**Issue by vkuznecovas** [mysteriumnetwork/api#82]
At the moment it's not possible to add multiple proposals with different service types to discovery. The way discovery is currently structured means that we're updating an existing proposal instead of adding a  new one.

To fix this issue, we'll need to change the proposal in such a way, that we're listing all the service types available for the given provider. 

Currently, the proposal endpoint returns a single object for provider, like so
```json
{
    "format": "service-proposal/v1",
    "id": 1,
    "payment_method": {
        "duration": 3600000000000,
        "price": {
            "amount": 12500000,
            "currency": "MYST"
        }
    },
    "payment_method_type": "PER_TIME",
    "provider_contacts": [
        {
            "definition": {
                "broker_addresses": [
                    "nats://testnet-broker.mysterium.network:4222"
                ],
                "topic": "0x0000000000000000000000000000000000000000"
            },
            "type": "nats/v1"
        }
    ],
    "provider_id": "0x0000000000000000000000000000000000000000",
    "service_definition": {
        "location": {
            "country": "US"
        },
        "location_originate": {
            "country": "US"
        },
        "protocol": "udp",
        "session_bandwidth": 83886080
    },
    "service_type": "openvpn"
}
```

I'd suggest changing the structure to the following:

```json
{
    "format": "service-proposal/v2",
    "id": 1,
    "provider_id": "0x0000000000000000000000000000000000000000",
    "provider_contacts": [
        {
            "definition": {
                "broker_addresses": [
                    "nats://testnet-broker.mysterium.network:4222"
                ],
                "topic": "0x0000000000000000000000000000000000000000"
            },
            "type": "nats/v1"
        }
    ],
    "services": [
        {
            "service_definition": {
                "location": {
                    "country": "US"
                },
                "location_originate": {
                    "country": "US"
                },
                "protocol": "udp",
                "session_bandwidth": 83886080
            },
            "service_type": "openvpn",
            "payment_method": {
                "duration": 3600000000000,
                "price": {
                    "amount": 12500000,
                    "currency": "MYST"
                },
                "payment_method_type": "PER_TIME"
            }
        },
        {
            "service_definition": {
                "location": {
                    "country": "US"
                },
                "location_originate": {
                    "country": "US"
                },
                "protocol": "udp",
                "session_bandwidth": 83886080
            },
            "service_type": "noop",
            "payment_method": {
                "duration": 3600000000000,
                "price": {
                    "amount": 12500000,
                    "currency": "MYST"
                },
                "payment_method_type": "PER_TIME"
            }
        }
    ]
}
```

*NOTE* this will break backwards compatibility. Depending on how much we need to be backwards compatible, we could just leave the v1 endpoints behind and add v2 versions to the discovery service.

This will also require changes to the register_proposal endpoint, as well as the ping endpoint. It will also require a bit of a rework of node logic, on how it manages the different services and interacts with the API.

Estimates:
* 3 days for the discovery changes(since python).
* 3-4 days for the changes in Node.

**Comment by vkuznecovas** [comment]
For separate proposals the following has to be done:

* Change primary keys on the Node table to a pair (node_key, service_type). This will probably break 90% of discovery code, but once the queries are adjusted everything should work properly.
* Change the node_availability table with extra column(service_type).
* Change the ping endpoint to accept a service type as well.
* Adjust the required queries in the discovery accordingly.

On node side, we'd probably only have to change the logic how pinging for activity occurs - so a minor change there.

Estimates:
* 2 days for discovery changes(since python).
* 1 day for Node changes.

This is a quicker way to achieve what we want, but also not as elegant as the first option.

**Comment by vkuznecovas** [comment]
> Alternate option - separate proposal for each new service type. Can you estimate amount of work and complexity for it?

added estimate to original writeup, as well as added an overview of the second approach.

**Comment by tadovas** [comment]
I would like to hear more opinions. @soffokl @zolia @Waldz ?

**Comment by soffokl** [comment]
I'd like to have different proposals for the different types of services, even for a single provider(option 2). 
It feels like it will be much simpler to operate smaller independent proposals.

**Comment by tadovas** [comment]
And why is that? Adding removing service will introduce additional operations, and for single proposal adding removing service will be simple proposal update

**Comment by vkuznecovas** [comment]
Note - the dashboard might need an adjustment in any case.

**Comment by soffokl** [comment]
> And why is that? Adding removing service will introduce additional operations, and for single proposal adding removing service will be simple proposal update

We already have adding and removing for proposal, no need for additional operation. 
But update we need new. 

I think option 2 is simpler because we have just a list of proposals and all of them similar. 
In the option 1 some proposals could be bigger, and if we are removing single service we need to update all related components. We need a new signature for the proposal, also promises use proposals and signatures there too, which should be updated too. 

But for option 1, it's just `add` or `delete`.

**Comment by tadovas** [comment]
promises should not use nor proposal nor signature.

**Comment by soffokl** [comment]
oh, right, we are using it only for issuing.

**Comment by vkuznecovas** [comment]
I'm considering the second option myself. The selling points for me:

* Faster.
* Existing structures do not have to change.
* With the outcome of discovery dying sometime anyway - maybe it makes sense to invest as little time into discovery/dashboard as possible?
* And the personal favorite: less work on python.

**Comment by zolia** [comment]
I would definitely stay with separate proposal for service. Easier logic, less interdependency. We may even assume that there will be separate services on different machines with the same providerID. 

Also, current update ping is not proper way IMHO. There should be no ping proposal, just register proposal. Receiving side can decide if it needs to be updated, but we always send our current proposal in full.

**Comment by Waldz** [comment]
- I suggest not to break `ServiceProposal` format, because it's designed to fit into smart contract.
- we dont want to invest ti API anymore, it will be thrown away
